---
- name: Install Docker
  hosts: ubuntu
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      tags:
        - install docker

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
      tags:
        - install docker

    - name: Add Docker GPG apt Key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
      tags:
        - install docker

    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      tags:
        - install docker

    - name: Update apt and install docker-ce
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      tags:
        - install docker

    - name: Docker run
      shell: docker run hello-world
      tags:
        - install docker

    - name: Uninstall Docker
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      tags:
        - drop docker
