---
- name: Install packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
  register: postgres_data

- name: Empty data dir
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: absent
  when: not postgres_data.stat.exists

- name: Initialize PostgreSQL
  ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  become: true
  become_user: postgres
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Utility present
  ansible.builtin.package:
    name: python3-psycopg2
    state: present

- name: Create db
  community.postgresql.postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: postgres

- name: Create db user  
  community.postgresql.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Adding privileges
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: false
    privs: all
  become: true
  become_user: postgres

- name: Create table
  community.postgresql.postgresql_table:
    name: test_table
    columns:
      - surname
      - name
      - date_birth
      - organization
    tablespace: ssd  
