---
- name: Installation and configuration php8.1-fpm
  hosts: test
  become: yes
  tasks:
    - name: Installation php8
      ansible.builtin.apt:
        name: php8.1-fpm
        state: present
        update_cache: true

    - name: Create file testdomain.ru
      ansible.builtin.file:
        path: "/etc/php/8.1/fpm/pool.d/"
        state: touch
        owner: test
        group: test

    - name: Copy file wwwconf
      ansible.builtin.copy:
        src: "/etc/php/8.1/fpm/pool.d/www.conf"
        dest: "/etc/php/8.1/fpm/pool.d/testdomain.ru.conf"
        owner: root
        group: root

    - name: Create file pool.php
      ansible.builtin.template:
        src: ../template/testdomain.ru.conf.j2
        dest: "/etc/php/8.1/fpm/pool.d/testdomain.ru.conf"
        owner: test
        group: test
      notify:
        - Restart php8

  handlers:
  - name: Restart php8
    ansible.builtin.service:
      name: php8.1-fpm
      state: restarted
      enabled: yes