---
- name: Create group and user
  hosts: test
  become: yes
  vars:
    password: qwerty
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tasks:
    - name: Create groups
      ansible.builtin.group:
        name: test
        state: present

    - name: Validate the sudoers file before saving 
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^admin'
        insertafter: '^%admin'
        line: '%test ALL=(ALL) ALL'
        validate: visudo -cf %s
          
    - name: Create user1
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512')}}"
        create_home: true
        shell: /bin/bash
        groups: sudo
        generate_ssh_key: yes
        ssh_key_bits: "{{ ssh_key_bits }}"
        ssh_key_file: "{{ ssh_key_file }}"
        append: true

    - name: Deploy SSH public key
      ansible.builtin.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        #key: "{{ lookup('file', '/home/{{ username }}/ssh.id_rsa.pub') }}"