---
- name: Installation PostgreSql
  hosts: database
  become: true
  vars:
    db_name: testdb
    db_user: myuser
    db_password: Qwerty123
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Create db
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: true
      become_user: postgres

    - name: Create db user  
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres  

  handlers: 
  - name: Restart postgres
    ansible.builtin.service:
      name: postgres
      state: restarted 

