---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restart
    enabled: yes

- name: Restart ufw 
  ansible.builtin.service:
    name: ufw
    state: restarted
    enabled: yes
