---
- name: Install php-fpm 8.1
  ansible.builtin.apt:
    name: "{{ name_package }}"
    state: present
    update_cache: yes

- name: Create directory
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    mode: 0755

- name: Create nginx.conf
  ansible.builtin.template:
    src: default.nginx.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - Restart nginx

- name: Create file info.php
  ansible.builtin.copy:
    dest: "{{ path }}/{{ file_name }}"
    content: "{{ content }}"